version: '3.1'

services:
  httpd:
    # image: php-fpm
    build: ./images/php-apache
    ports:
      - 8081:80
    volumes:
      - ./htdocs:/var/www/html/
    # depends_on:
    #   - db
    networks:
      - back-tier
   # docker network create apps-net
   # docker run -d --name php-apache --network apps-net -v C:\Users\fjavalencia\ohrmd_apps\html:/var/www/html/ -p 8081:80 ohrmd_apps-httpd:latest
   
  db:
    build: ./images/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    networks:
      - back-tier
    volumes:
      - db-data:/var/lib/mysql
      
      # docker network create apps-net
      # docker run -d --name mariadb --network dev-net -e MARIADB_ROOT_PASSWORD=superhr2023 -v db-data:/var/lib/mysql mariadb:10.6

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=100M
    # depends_on:
    #   - db
    networks:
      - back-tier

    # docker run -d --name phpmyadmin --network apps-net -e PMA_ARBITRARY=1 -p 8080:80 phpmyadmin

  # /var/lib/mysql
networks:
  # The presence of these objects is sufficient to define them
  # front-tier: {}
  back-tier: {}

volumes:
  db-data:

secrets:
   db_root_password:
     file: db_root_password.txt